spring:
  application:
    name: currency-exchange-spring-boot
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ''
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
